# Generated by Django 3.0.6 on 2020-05-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserviceapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_username',
        ),
    ]
