# Generated by Django 3.0.6 on 2020-05-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserviceapi', '0002_auto_20200527_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanrequest',
            old_name='request_account',
            new_name='request_owner_account',
        ),
    ]
