# Generated by Django 3.0.6 on 2020-05-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserviceapi', '0003_auto_20200527_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='post_owner',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='owner',
            new_name='comment_owner',
        ),
    ]
